SB3:
  PPO:
    Optuna:
      N_TRIALS: 10
      N_STARTUP_TRIALS: 5
      N_EVALUATIONS: 2
      N_TIMESTEPS: int(1e3)
      N_EVAL_EPISODES: 3
      
      Params:
        batch_size: 16
        n_steps: 64
        gamma: 0.95
        learning_rate: 6.00645744827779e-05
        lr_schedule: linear
        ent_coef: 1.024896115867073e-06
        clip_range: 0.3
        n_epochs: 1
        gae_lambda: 0.95
        max_grad_norm: 2
        vf_coef: 0.9464885226547327
        net_arch: small
        sde_sample_freq: -1
        ortho_init: True
        activation_fn: elu



  Value:  -22.03333282470703
  Params: 
    batch_size: 32
    n_steps: 1024
    gamma: 0.999
    learning_rate: 0.017149590786186934
    lr_schedule: linear
    ent_coef: 2.640243434153508e-05
    clip_range: 0.3
    n_epochs: 5
    gae_lambda: 0.92
    max_grad_norm: 0.8
    vf_coef: 0.05394794835192018
    net_arch: small
    sde_sample_freq: 32
    ortho_init: True
    activation_fn: leaky_relu



    Number of finished trials:  10
Best trial:
  Value:  -43.839996337890625
  Params: 
    batch_size: 512
    n_steps: 2048
    gamma: 0.995
    learning_rate: 0.033096203060840206
    lr_schedule: constant
    ent_coef: 0.09189040645058641
    clip_range: 0.4
    cl_schedule: linear
    n_epochs: 1
    gae_lambda: 0.92
    max_grad_norm: 0.8
    vf_coef: 0.046787048773584305
    net_arch: small
    sde_sample_freq: 16
    ortho_init: True
    activation_fn: elu