SB3:
  PPO:
    Optuna:
      N_TRIALS: 10
      N_STARTUP_TRIALS: 5
      N_EVALUATIONS: 2
      N_TIMESTEPS: int(1e3)
      N_EVAL_EPISODES: 3
      
      Params:
        batch_size: 16
        n_steps: 64
        gamma: 0.95
        learning_rate: 6.00645744827779e-05
        lr_schedule: linear
        ent_coef: 1.024896115867073e-06
        clip_range: 0.3
        n_epochs: 1
        gae_lambda: 0.95
        max_grad_norm: 2
        vf_coef: 0.9464885226547327
        net_arch: small
        sde_sample_freq: -1
        ortho_init: True
        activation_fn: elu
